"""
Converts the raw Basil SVG source (icons-source/{Outline,Solid}/{Category}/*.svg)
into TypeScript registries the Icon component consumes.

Run from packages/icons/: python3 scripts/build-icons.py
Re-run whenever icons-source/ is updated (e.g. a new Basil version).
"""
import os
import re
import json

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PKG_ROOT = os.path.dirname(SCRIPT_DIR)
SOURCE = os.path.join(PKG_ROOT, "icons-source")
OUT = os.path.join(PKG_ROOT, "src", "generated")

STYLES = ["Outline", "Solid"]


def slugify(name):
    # "Adobe-After-effects" -> "adobe-after-effects"
    # "At-sign" -> "at-sign"
    name = re.sub(r"[^a-zA-Z0-9\-]+", "-", name)
    name = re.sub(r"-+", "-", name).strip("-")
    return name.lower()


def extract_inner_svg(svg_text):
    """Pull out everything between <svg ...> and </svg>, recolor black to
    currentColor so the icon inherits color from CSS (like every other
    component in this DS), leave fill="none" alone (that's the outer
    canvas, not an icon color)."""
    match = re.search(r"<svg[^>]*>(.*)</svg>", svg_text, re.DOTALL)
    inner = match.group(1).strip() if match else svg_text.strip()
    inner = re.sub(r'fill="black"', 'fill="currentColor"', inner)
    inner = re.sub(r'stroke="black"', 'stroke="currentColor"', inner)
    return inner


registry = {}  # style -> { icon-name: inner-svg-markup }
manifest = {}  # style -> { icon-name: category }  (for docs/gallery)

for style in STYLES:
    style_key = style.lower()
    registry[style_key] = {}
    manifest[style_key] = {}
    style_dir = os.path.join(SOURCE, style)
    if not os.path.isdir(style_dir):
        continue
    for category in sorted(os.listdir(style_dir)):
        category_dir = os.path.join(style_dir, category)
        if not os.path.isdir(category_dir):
            continue
        for filename in sorted(os.listdir(category_dir)):
            if not filename.endswith(".svg"):
                continue
            icon_name = slugify(filename[:-4])
            svg_text = open(os.path.join(category_dir, filename)).read()
            registry[style_key][icon_name] = extract_inner_svg(svg_text)
            manifest[style_key][icon_name] = category

os.makedirs(OUT, exist_ok=True)


def write_registry_ts(style_key):
    path = os.path.join(OUT, f"{style_key}.ts")
    names = sorted(registry[style_key].keys())
    with open(path, "w") as f:
        f.write(
            f"// Auto-generated by scripts/build-icons.py — do not edit by hand.\n"
        )
        f.write(f"export const {style_key}Icons: Record<string, string> = {{\n")
        for name in names:
            f.write(f"  {json.dumps(name)}: {json.dumps(registry[style_key][name])},\n")
        f.write("};\n\n")
        f.write(
            f"export type {style_key.capitalize()}IconName = keyof typeof {style_key}Icons;\n"
        )
    print(f"wrote {path} ({len(names)} icons)")


for style_key in ["outline", "solid"]:
    write_registry_ts(style_key)

manifest_path = os.path.join(OUT, "manifest.json")
with open(manifest_path, "w") as f:
    json.dump(manifest, f, indent=2)
print(f"wrote {manifest_path}")
