import type { Preview } from '@storybook/react-vite';

// Generated by @theya/tokens (packages/tokens). Run `pnpm --filter
// @theya/tokens build` at least once before starting Storybook, or
// these files won't exist yet.
import '../../tokens/build/css/variables.css';
import '../../tokens/build/css/variables-dark.css';

// Self-hosted Clash Grotesk (replaces the Inter/Google-Fonts import —
// see packages/tokens/fonts/fonts.css for the @font-face rule and
// packages/tokens/fonts/clash-grotesk/LICENSE.txt for licensing).
import '../../tokens/fonts/fonts.css';

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
